### ISSUE TITLE
Transparent background support?

### ISSUE THREAD

**Issue by starinspace** [n00mkrad/cupscale#39]
I have looked a bit on it, but is there any transparent background support? I do upscale images that has transparent backgrounds and its a little problematic cause its a few hundreds of images I need to cut out background to make it transparent again.

If not, I would want that feature. :)

**Comment by n00mkrad** [comment]
There is alpha support. Both 8-bit and binary/ternary (1/2 bit).

**Comment by starinspace** [comment]
Okey.

Well. I saw your answer, and I have tried, but is it in the "General Settings" > "Enable Alpha"? I did try 0, 1, 2 and 3. It uses the background color. I also tried in "Full (8-bit)" Full, Binary and Temary. Same thing. Or have I missed something? I do use a png as input and same as output.

**Comment by Randalmcdaniel** [comment]
Bruh i have tried literally every option in cupscale, it only seems to retain transparency if i save the file as jpeg or png (i forget which, whichever one it defaults to).

The upscale seems to work but the mountains and trees all have black square bases

i tried differential alpha, seperate alpha, all the others. I even tried every compression format available DX1-DX5

I even downloaded ESRGAN models that said they were designed for DDS textures. No luck. 

Im a noob but upscaling textures in games has been super easy with cupscale. Its just unfortunate i cant upscale any texture that has a transparency in it. I am desperate to know how to make it work.

so i googled it and google pretty much said upscaling transparency is impossible or something. Yet people have done it in other games so i know thats not right..

Any help would be appreciated. my recycle bin is filled with over 100 files of the same picture because i have tried literally every combination and setting in cupscale to get this to work without any luck

I even tried renaming the png file extension to DDS and it seemed to work but then the texture came out mutated when in the game

Thanks for reading
